name: Deploy Model

on:
  push:
    branches:
      - main  # 监听主分支的提交
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # 更新到 v3

      - name: Set up Python
        uses: actions/setup-python@v4  # 更新到 v4
        with:
          python-version: '3.9'  # 使用您需要的 Python 版本

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask application
        env:
          HOST: 0.0.0.0  # 设置 host
          PORT: 5005     # 设置 port
        run: |
          nohup python app.py &
