name: Deploy Flask App with ngrok

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        env:
          FLASK_APP: app.py
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &

      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start ngrok with fixed subdomain
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_SUBDOMAIN: ${{ secrets.NGROK_SUBDOMAIN }}
        run: |
          ngrok authtoken $NGROK_AUTH_TOKEN
          nohup ngrok http --subdomain=${NGROK_SUBDOMAIN} 5000 > /dev/null &

      - name: Display fixed ngrok URL
        run: echo "Access your app at: https://${{ secrets.NGROK_SUBDOMAIN }}.ngrok.io"
